from __future__ import annotations

import json
import re
import shlex
import shutil
from copy import deepcopy
from pathlib import Path
from typing import Any, Dict, Iterable, List, Optional, Tuple

from github_reader import fetch_repo_context
from bridge_templates import (
    render_bridge_script as _render_bridge_script_template,
    render_embedded_ui_html as _render_embedded_ui_html_template,
    render_ui_runner_script as _render_ui_runner_script_template,
)


_CODE_BLOCK_RE = re.compile(r"```(?:bash|sh|shell|powershell|pwsh|cmd)?\s*\n(.*?)```", re.IGNORECASE | re.DOTALL)
_FLAG_RE = re.compile(r"--([a-zA-Z0-9_-]+)(?:[=\s]+([^\s]+))?")
_PYTHON_CMD_INLINE_RE = re.compile(
    r"(?:^|[\s`])(python|python3|py)\s+([A-Za-z0-9_./\\-]+\.py)\b",
    re.IGNORECASE,
)
_COMMAND_STARTERS = (
    "python ",
    "python3 ",
    "py ",
    "uvicorn ",
    "gunicorn ",
    "streamlit ",
    "gradio ",
    "flask run",
    "django-admin ",
    "uv run ",
    "npm run ",
    "pnpm ",
    "yarn ",
    "node ",
    "bash ",
    "sh ",
    "./",
    "make ",
    "docker compose ",
    "docker-compose ",
)
_SETUP_PREFIXES = (
    "python -m venv ",
    "python3 -m venv ",
    "py -m venv ",
    "pip install ",
    "pip3 install ",
    "python -m pip install ",
    "python3 -m pip install ",
    "uv pip install ",
    "poetry install",
    "poetry lock",
    "npm install",
    "pnpm install",
    "yarn install",
    "conda create ",
    "conda install ",
    "apt ",
    "apt-get ",
    "brew ",
    "choco ",
    "winget ",
    "git clone ",
    "cd ",
)
_WINDOWS_ACTIVATE_RE = re.compile(
    r"(?P<path>[A-Za-z0-9._\\/-]+)[/\\]scripts[/\\]activate(?:\.(?:ps1|bat|cmd))?$",
    re.IGNORECASE,
)
_POSIX_ACTIVATE_RE = re.compile(r"(?P<path>[A-Za-z0-9._\\/-]+)/bin/activate$", re.IGNORECASE)
_CONDA_ACTIVATE_RE = re.compile(r"^conda\s+activate\s+(?P<name>[A-Za-z0-9._-]+)$", re.IGNORECASE)
_README_LINE_SPLIT_RE = re.compile(r"[\r\n]+")
_DEFAULT_WORKING_DIR = "."
_DEFAULT_PROJECT_ROOT_REL = "../.."
_TEMPLATE_ASSETS_DIR = Path(__file__).resolve().parent / "bridge_template_assets" / "assets"
_BRIDGE_README_CONTENT = (
    "# AIUI Bridge Bundle\n\n"
    "Generated by AIUI. This folder is non-invasive and does not modify project source files.\n\n"
    "Semantics:\n"
    "- `AUI_UI_ENTRY.json` is a static export entry for embedding/rendering snapshots.\n"
    "- `ui_runner.py` is the runtime controller for start/stop/log/anchors/rollback.\n\n"
    "## Files\n"
    "- `aui_bridge.py`: bridge launcher wrapper\n"
    "- `aui_bridge_config.json`: startup command/flags config\n"
    "- `aui_ui_protocol.json`: status bar + controls protocol\n\n"
    "## Usage\n"
    "```powershell\n"
    "# optional check\n"
    "python ./.aui-dashboard/bridge/aui_bridge.py --print-command\n"
    "python ./.aui-dashboard/bridge/aui_bridge.py\n"
    "```\n"
)
_UI_README_CONTENT = (
    "# AIUI Standalone UI\n\n"
    "This is a standalone runtime UI (no recent projects list).\n"
    "It reads:\n"
    "- `../bridge/aui_ui_protocol.json`\n"
    "- `../bridge/bridge_runtime.log.jsonl`\n\n"
    "Important:\n"
    "- `AUI_UI_ENTRY.json` is static integration metadata.\n"
    "- Real runtime control is provided by this `ui_runner.py`.\n\n"
    "## Run\n"
    "```powershell\n"
    "python ./.aui-dashboard/ui/ui_runner.py\n"
    "```\n"
    "This opens a local web page that shows status bar, anchors and logs.\n"
)


def _dedupe_keep_order(items: Iterable[str]) -> List[str]:
    seen = set()
    out: List[str] = []
    for item in items:
        key = item.strip()
        if not key or key in seen:
            continue
        seen.add(key)
        out.append(key)
    return out


def _split_command(cmd: str) -> List[str]:
    text = (cmd or "").strip()
    if not text:
        return []
    try:
        return shlex.split(text)
    except Exception:
        return text.split()


def _looks_like_activation_command(line: str) -> bool:
    text = (line or "").strip().strip("\"'")
    low = text.lower()
    if low.startswith("source "):
        tail = text[7:].strip()
        if _POSIX_ACTIVATE_RE.search(tail):
            return True
    if _WINDOWS_ACTIVATE_RE.search(text):
        return True
    if _CONDA_ACTIVATE_RE.fullmatch(text):
        return True
    if low in {"poetry shell", "pipenv shell"}:
        return True
    return False


def _is_setup_command(command: str) -> bool:
    low = (command or "").strip().lower()
    if not low:
        return True
    if _looks_like_activation_command(low):
        return True
    return any(low.startswith(prefix) for prefix in _SETUP_PREFIXES)


def _normalize_venv_dir(raw_path: str) -> str:
    path = (raw_path or "").strip().replace("\\", "/")
    while path.startswith("./"):
        path = path[2:]
    while path.startswith("../"):
        path = path[3:]
    path = path.strip("/")
    if not path:
        return ""
    if "/" in path:
        return path.split("/")[-1]
    return path


def _extract_venv_hint(readme_text: str) -> Dict[str, str]:
    if not readme_text:
        return {}

    def _iter_lines() -> Iterable[str]:
        for block in _CODE_BLOCK_RE.findall(readme_text):
            for raw_line in block.splitlines():
                line = raw_line.strip()
                if line:
                    yield line
        for raw_line in readme_text.splitlines():
            line = raw_line.strip()
            if line.startswith("$ "):
                yield line[2:].strip()

    for line in _iter_lines():
        text = line.strip().strip("\"'")
        low = text.lower()
        if low.startswith("source "):
            tail = text[7:].strip().strip("\"'")
            m = _POSIX_ACTIVATE_RE.search(tail)
            if m:
                venv_dir = _normalize_venv_dir(m.group("path"))
                if venv_dir:
                    return {"type": "venv_path", "venv_dir": venv_dir, "activation_command": line}
        m = _WINDOWS_ACTIVATE_RE.search(text)
        if m:
            venv_dir = _normalize_venv_dir(m.group("path"))
            if venv_dir:
                return {"type": "venv_path", "venv_dir": venv_dir, "activation_command": line}
        m = _CONDA_ACTIVATE_RE.fullmatch(text)
        if m:
            return {"type": "conda", "env_name": m.group("name"), "activation_command": line}
        if low in {"poetry shell", "pipenv shell"}:
            return {"type": "shell_manager", "manager": low.split()[0], "activation_command": line}
    return {}


def _build_pre_run_checklist(
    readme_text: str,
    recommended_command: str,
    venv_hint: Dict[str, str],
) -> List[str]:
    text = readme_text or ""
    low = text.lower()
    items: List[str] = []

    # Always state boundary clearly.
    items.append(
        "AIUI is non-intrusive: it only uses .aui-dashboard files and will not modify your project source files."
    )

    if venv_hint:
        activation = str(venv_hint.get("activation_command") or "").strip()
        if activation:
            items.append(f"Activate environment before run: `{activation}`.")

    if recommended_command:
        items.append(f"Run command from README analysis: `{recommended_command}`.")

    # Lightweight README-derived checks (no auto mutation, only reminders).
    if "github token" in low or "gh token" in low or "gittoken" in low:
        items.append("README mentions GitHub token. Confirm required token env vars are set before run.")
    if "openai_api_key" in low or "api key" in low or "apikey" in low:
        items.append("README mentions API key setup. Confirm required provider keys are configured.")
    if "requirements.txt" in low or "pip install" in low or "npm install" in low or "pnpm install" in low:
        items.append("Dependencies may be required by README. Ensure install steps are completed manually.")
    if "resources" in low and ("mkdir" in low or "directory" in low or "folder" in low or "目录" in text):
        items.append("README appears to require a `resources` directory. Confirm it exists and contains needed input data.")
    if "result" in low and ("directory" in low or "folder" in low or "目录" in text):
        items.append("README references output folder `result`. Confirm output path assumptions before run.")
    if ".env" in low or "environment variable" in low or "环境变量" in text:
        items.append("README references environment variables/.env. Confirm required variables are present.")

    # Try to extract imperative checklist-like lines from README.
    for raw_line in _README_LINE_SPLIT_RE.split(text):
        line = (raw_line or "").strip()
        if not line:
            continue
        l = line.lower()
        if len(items) >= 10:
            break
        # Keep concise high-signal lines only.
        if any(
            kw in l
            for kw in (
                "make sure",
                "ensure",
                "before run",
                "prerequisite",
                "需要先",
                "请先",
                "手动",
                "must",
            )
        ):
            cleaned = line.lstrip("-*0123456789. ").strip()
            if cleaned and len(cleaned) <= 180:
                items.append(cleaned)

    return _dedupe_keep_order(items)


def _extract_commands_from_readme(readme_text: str) -> List[str]:
    if not readme_text:
        return []
    candidates: List[str] = []

    # fenced code block lines
    for block in _CODE_BLOCK_RE.findall(readme_text):
        for raw_line in block.splitlines():
            line = raw_line.strip()
            if not line or line.startswith("#"):
                continue
            if line.startswith("$ "):
                line = line[2:].strip()
            lower = line.lower()
            if lower.startswith(_COMMAND_STARTERS):
                if not _is_setup_command(line):
                    candidates.append(line)

    # plain lines with "$ command"
    for raw_line in readme_text.splitlines():
        line = raw_line.strip()
        if not line.startswith("$ "):
            continue
        line = line[2:].strip()
        lower = line.lower()
        if lower.startswith(_COMMAND_STARTERS):
            if not _is_setup_command(line):
                candidates.append(line)

    # inline command mentions such as: "run with `python core.py`"
    for m in _PYTHON_CMD_INLINE_RE.finditer(readme_text):
        interpreter = m.group(1)
        script = m.group(2)
        line = f"{interpreter} {script}"
        if not _is_setup_command(line):
            candidates.append(line)

    return _dedupe_keep_order(candidates)


def _commands_from_repo_structure(repo_brief: Dict[str, Any]) -> List[str]:
    names: set[str] = set()
    python_file_paths: List[str] = []
    for it in repo_brief.get("top_level_items") or []:
        if not isinstance(it, dict):
            continue
        name = (it.get("name") or "").strip()
        if name:
            names.add(name.lower())
        if (it.get("type") or "") == "file":
            path = (it.get("path") or name or "").strip()
            if path.lower().endswith(".py") and not path.lower().endswith("__init__.py"):
                python_file_paths.append(path)

    out: List[str] = []
    if "docker-compose.yml" in names or "docker-compose.yaml" in names:
        out.append("docker compose up")
    if "package.json" in names:
        out.extend(["npm run dev", "npm start"])
    if "makefile" in names:
        out.append("make run")
    if "start.sh" in names:
        out.append("bash start.sh")
    if "main.py" in names:
        out.append("python main.py")
    if "app.py" in names:
        out.append("python app.py")
    if "manage.py" in names:
        out.append("python manage.py runserver")
    if "pyproject.toml" in names and "app.py" not in names and "main.py" not in names:
        out.append("python -m app")

    # Generic python entry candidates.
    strong_names = ("core.py", "main.py", "app.py", "run.py", "server.py", "start.py", "cli.py", "manage.py")
    lower_paths = [p.lower() for p in python_file_paths]
    for n in strong_names:
        for i, p in enumerate(lower_paths):
            if p == n:
                out.append(f"python {python_file_paths[i]}")

    uniq_python = _dedupe_keep_order(python_file_paths)
    if len(uniq_python) == 1:
        out.append(f"python {uniq_python[0]}")
    for p in sorted(uniq_python, key=lambda x: (x.count("/"), x.count("\\"), len(x)))[:5]:
        out.append(f"python {p}")

    return _dedupe_keep_order(out)


def _choose_recommended_command(readme_commands: List[str], structure_commands: List[str]) -> Tuple[str, List[str]]:
    # Priority rule:
    # 1) README explicit run commands (in source order)
    # 2) Top-level structure heuristic
    # 3) Fallback
    if readme_commands:
        candidates = _dedupe_keep_order([*readme_commands, *structure_commands, "python main.py"])
        return readme_commands[0], candidates
    if structure_commands:
        candidates = _dedupe_keep_order([*structure_commands, "python main.py"])
        return structure_commands[0], candidates
    return "python main.py", ["python main.py"]


def _normalize_flag_value(raw_value: Optional[str]) -> Any:
    if raw_value is None:
        return True
    txt = raw_value.strip()
    if not txt:
        return True
    low = txt.lower()
    if low in {"true", "false"}:
        return low == "true"
    if re.fullmatch(r"\d+", txt):
        try:
            return int(txt)
        except Exception:
            return txt
    if re.fullmatch(r"\d+\.\d+", txt):
        try:
            return float(txt)
        except Exception:
            return txt
    return txt.strip("\"'")


def _extract_flag_defaults(command: str) -> Dict[str, Any]:
    defaults: Dict[str, Any] = {}
    for name, value in _FLAG_RE.findall(command or ""):
        key = name.replace("-", "_").strip()
        if not key:
            continue
        defaults[key] = _normalize_flag_value(value)
    return defaults


def _control_type(name: str, default: Any) -> str:
    low = (name or "").lower()
    if isinstance(default, bool):
        return "switch"
    if any(k in low for k in ("port", "workers", "batch", "steps", "epochs", "num", "size")):
        return "number"
    if isinstance(default, (int, float)):
        return "number"
    return "text"


def _build_controls(flag_defaults: Dict[str, Any]) -> List[Dict[str, Any]]:
    controls: List[Dict[str, Any]] = []
    for key, default in flag_defaults.items():
        controls.append(
            {
                "id": key,
                "label": key.replace("_", " ").title(),
                "type": _control_type(key, default),
                "flag": f"--{key.replace('_', '-')}",
                "default": default,
                "source": "launch_command",
            }
        )
    return controls


def _build_launch_profile(command: str) -> Dict[str, Any]:
    cmd_tokens = _split_command(command)
    command_base: List[str] = []
    if cmd_tokens:
        for tok in cmd_tokens:
            if tok.startswith("--"):
                break
            command_base.append(tok)
    return {
        "command_base": command_base,
        "passthrough_args": [],
        "flag_defaults": _extract_flag_defaults(command),
    }


def _safe_dict(value: Any) -> Dict[str, Any]:
    return value if isinstance(value, dict) else {}


def _safe_list_of_text(values: Any) -> List[str]:
    if not isinstance(values, list):
        return []
    return [str(x) for x in values]


def _build_launch_metadata(
    *,
    command: str,
    candidate_commands: Optional[List[str]] = None,
    working_dir: str = _DEFAULT_WORKING_DIR,
    venv_hint: Optional[Dict[str, Any]] = None,
) -> Dict[str, Any]:
    profile = _build_launch_profile(command)
    flag_defaults = profile["flag_defaults"]
    return {
        "launch_profile": {
            "recommended_command": command,
            "candidate_commands": _dedupe_keep_order(candidate_commands or [command]),
            "command_base": profile["command_base"],
            "passthrough_args": profile["passthrough_args"],
            "flag_defaults": flag_defaults,
            "working_dir": working_dir,
            "venv_hint": _safe_dict(venv_hint),
        },
        "controls": _build_controls(flag_defaults),
        "launch": {
            "command": command,
            "working_dir": working_dir,
            "supports_stdin": True,
        },
    }


def _build_bridge_config(
    *,
    thread_id: str,
    project_root: Path,
    launch_profile: Dict[str, Any],
) -> Dict[str, Any]:
    venv_hint = _safe_dict(launch_profile.get("venv_hint"))
    venv_dir = str(venv_hint.get("venv_dir") or "").strip()
    activation_hint = str(venv_hint.get("activation_command") or "").strip()
    return {
        "version": 1,
        "thread_id": thread_id,
        # Keep relative by default for portability across machines/folders.
        "project_root": _DEFAULT_PROJECT_ROOT_REL,
        "project_root_hint_abs": str(project_root),
        "project_root_mode": "relative_to_bridge_dir",
        "command_base": launch_profile.get("command_base") or [],
        "passthrough_args": launch_profile.get("passthrough_args") or [],
        "flag_defaults": launch_profile.get("flag_defaults") or {},
        "venv_dir": venv_dir,
        "activation_hint": activation_hint,
        "python_interpreter": "",
        "dashboard_hook_url": "",
    }


def _sanitize_text(text: Any, fallback: str = "") -> str:
    raw = str(text or "").replace("\r\n", "\n").replace("\r", "\n").strip()
    if not raw:
        return fallback
    # Drop hard control chars to keep protocol payload safe and deterministic.
    cleaned = "".join(ch for ch in raw if ch == "\n" or ord(ch) >= 32)
    cleaned = cleaned.strip()
    return cleaned or fallback


def _runtime_event_stages() -> List[Dict[str, Any]]:
    # Event-driven status stages (not AIUI planning steps):
    # lifecycle starting -> first stdio output -> lifecycle exited
    return [
        {
            "id": "process_starting",
            "label": "Process Starting",
            "description": "Bridge has launched the target command.",
            "anchor_name": "Process Starting",
            "trigger_keyword": "starting",
            "match_rules": [
                {
                    "type": "lifecycle",
                    "event": "starting",
                }
            ],
            "match_patterns": [r"\bstarting\b"],
        },
        {
            "id": "first_output",
            "label": "First Output",
            "description": "First stdout/stderr output is received from the project.",
            "anchor_name": "First Output",
            "trigger_keyword": "stdout",
            "match_rules": [
                {
                    "type": "stdio",
                    "stream_regex": "^(stdout|stderr)$",
                    "has_line": True,
                },
                {
                    "stream_regex": "^(bridge_stdout|bridge_stderr)$",
                    "line_regex": r"\[(stdout|stderr)\]\s+",
                },
            ],
            "match_patterns": [r"\[(stdout|stderr)\]"],
        },
        {
            "id": "process_exited",
            "label": "Process Exited",
            "description": "Target process has exited (success or failure).",
            "anchor_name": "Process Exited",
            "trigger_keyword": "exited",
            "match_rules": [
                {
                    "type": "lifecycle",
                    "event": "exited",
                }
            ],
            "match_patterns": [r"\bexited\b"],
        },
    ]


def _build_status_stages(plan_steps: List[Dict[str, Any]]) -> List[Dict[str, Any]]:
    _ = plan_steps
    return _runtime_event_stages()


def _default_sdui_actions() -> List[Dict[str, Any]]:
    return [
        {
            "id": "interaction_required",
            "mode": "input",
            "title": "Input Required",
            "description": "Terminal is waiting for user input.",
            "ui_component": "input_prompt",
        },
        {
            "id": "progress_update",
            "mode": "progress",
            "title": "Progress Update",
            "description": "Update progress bar from parsed runtime logs.",
            "ui_component": "progress_bar",
        },
        {
            "id": "stage_change",
            "mode": "stage",
            "title": "Stage Change",
            "description": "Highlight current stage based on parsed runtime logs.",
            "ui_component": "stage_pills",
        },
        {
            "id": "error_detected",
            "mode": "recover",
            "title": "AI Diagnose",
            "description": "Suggest auto rollback and retry prompt when runtime errors are detected.",
            "ui_component": "diagnose_modal",
        },
        {
            "id": "anchors_catalog",
            "mode": "anchor",
            "title": "Anchor Catalog",
            "description": "Display available rollback anchors captured at stage transitions.",
            "ui_component": "anchor_list",
        },
        {
            "id": "rollback_anchor",
            "mode": "anchor",
            "title": "Rollback By Anchor",
            "description": "Rollback to a selected anchor and replay recorded stdin history.",
            "ui_component": "anchor_rollback_button",
        },
    ]


def _default_intent_rules(stages: List[Dict[str, Any]]) -> List[Dict[str, Any]]:
    rules: List[Dict[str, Any]] = [
        {
            "id": "progress_percent",
            "regex": r"(?i)(?:progress|\u8fdb\u5ea6)\s*[:\uff1a]?\s*(\d{1,3})\s*%",
            "emit": {
                "type": "ui_state",
                "update": "progress",
                "progress_group": 1,
            },
        },
        {
            "id": "interaction_required",
            "regex": r"(?i)(enter\s+password|password\s*:|\u8bf7\u8f93\u5165|\u8f93\u5165\u5bc6\u7801|press\s+enter|wait\s+for\s+user|input\s*:|you\s*:)",
            "emit": {
                "type": "ui_state",
                "update": "interaction_required",
                "mode": "input",
            },
        },
        {
            "id": "error_detected",
            "regex": r"(?i)(traceback|exception|error|failed|fatal|module\s*not\s*found|no such file|permission denied)",
            "emit": {
                "type": "ui_state",
                "update": "error_detected",
                "ask_auto_recover": True,
            },
        },
    ]

    for idx, stage in enumerate(stages):
        sid = str(stage.get("id") or f"stage_{idx + 1}")
        keyword = str(stage.get("trigger_keyword") or "").strip()
        if keyword:
            regex = re.escape(keyword)
        else:
            label = str(stage.get("label") or sid).strip()
            regex = re.escape(label) if label else sid
        rules.append(
            {
                "id": f"stage_change_{sid}",
                "regex": rf"(?i){regex}",
                "emit": {
                    "type": "ui_state",
                    "update": "stage_change",
                    "stage_index": idx,
                    "stage_id": sid,
                    "stage_label": str(stage.get("label") or sid),
                },
            }
        )
    return rules


def build_bridge_preview(
    *,
    repo_url: str,
    user_notes: str = "",
    plan_steps: Optional[List[Dict[str, Any]]] = None,
    repo_ctx: Optional[Dict[str, Any]] = None,
) -> Dict[str, Any]:
    context = repo_ctx or fetch_repo_context(repo_url)
    repo_brief = context.get("repo_brief") or {}
    readme_text = context.get("readme_text") or ""

    readme_commands = _extract_commands_from_readme(readme_text)
    structure_commands = _commands_from_repo_structure(repo_brief)
    recommended_command, candidates = _choose_recommended_command(readme_commands, structure_commands)
    venv_hint = _extract_venv_hint(readme_text)
    pre_run_checklist = _build_pre_run_checklist(
        readme_text=readme_text,
        recommended_command=recommended_command,
        venv_hint=venv_hint,
    )
    launch_meta = _build_launch_metadata(
        command=recommended_command,
        candidate_commands=candidates,
        working_dir=_DEFAULT_WORKING_DIR,
        venv_hint=venv_hint,
    )

    stages = _build_status_stages(plan_steps or [])
    actions = _default_sdui_actions()
    intent_rules = _default_intent_rules(stages)

    description = _sanitize_text(repo_brief.get("description"), fallback="")
    core_functionality = description or _sanitize_text(repo_brief.get("full_name"), fallback="Unknown project")

    preview = {
        "version": 1,
        "repo_url": repo_url,
        "core_functionality": core_functionality,
        "execution_flow": [s["label"] for s in stages],
        "analysis_source": {
            "repo_name": repo_brief.get("full_name") or repo_brief.get("local_path") or "unknown",
            "default_branch": repo_brief.get("default_branch") or "",
            "readme_chars": len(readme_text),
            "source_type": repo_brief.get("source_type") or "unknown",
            "readme_file": repo_brief.get("readme_file") or "",
            "startup_files": repo_brief.get("startup_files") or [],
            "top_level_items_count": len(repo_brief.get("top_level_items") or []),
            "user_notes": user_notes,
        },
        "launch_profile": launch_meta["launch_profile"],
        "ui_protocol": {
            "version": 1,
            "is_layered": True,
            "non_intrusive": True,
            "pre_run_checklist": pre_run_checklist,
            "anchor_settings": {
                "dedupe_window_seconds": 2.0,
                "similarity_threshold": 0.88,
                "naming": "step_index_title",
                "page_size": 8,
            },
            "status_bar": {"stages": stages},
            "actions": actions,
            "intent_rules": intent_rules,
            "controls": launch_meta["controls"],
            "launch": launch_meta["launch"],
        },
    }
    return preview


def apply_launch_command_override(preview: Dict[str, Any], override_command: str) -> Dict[str, Any]:
    text = (override_command or "").strip()
    if not text:
        return preview

    updated = deepcopy(preview)

    launch_profile = _safe_dict(updated.get("launch_profile"))
    deduped_candidates = _dedupe_keep_order([text, *_safe_list_of_text(launch_profile.get("candidate_commands"))])
    launch_meta = _build_launch_metadata(
        command=text,
        candidate_commands=deduped_candidates,
        working_dir=str(launch_profile.get("working_dir") or _DEFAULT_WORKING_DIR),
        venv_hint=_safe_dict(launch_profile.get("venv_hint")),
    )
    updated["launch_profile"] = launch_meta["launch_profile"]

    ui_protocol = _safe_dict(updated.get("ui_protocol"))
    ui_protocol["controls"] = launch_meta["controls"]
    launch_cfg = _safe_dict(ui_protocol.get("launch"))
    supports_stdin = bool(launch_cfg.get("supports_stdin", True))
    launch_cfg.update(launch_meta["launch"])
    launch_cfg["supports_stdin"] = supports_stdin
    ui_protocol["launch"] = launch_cfg
    updated["ui_protocol"] = ui_protocol
    return updated


def render_bridge_script() -> str:
    return _render_bridge_script_template()


def render_embedded_ui_html() -> str:
    return _render_embedded_ui_html_template()


def render_ui_runner_script() -> str:
    return _render_ui_runner_script_template()


def _copy_template_assets(target_ui_dir: Path) -> Optional[Path]:
    if not _TEMPLATE_ASSETS_DIR.exists():
        return None
    target_assets_dir = target_ui_dir / "assets"
    for src in _TEMPLATE_ASSETS_DIR.rglob("*"):
        rel = src.relative_to(_TEMPLATE_ASSETS_DIR)
        dst = target_assets_dir / rel
        if src.is_dir():
            dst.mkdir(parents=True, exist_ok=True)
            continue
        dst.parent.mkdir(parents=True, exist_ok=True)
        # Keep user-customized runtime backgrounds if they already exist.
        if dst.exists():
            continue
        shutil.copy2(src, dst)
    return target_assets_dir


def write_bridge_bundle(
    *,
    target_bridge_dir: Path,
    thread_id: str,
    project_root: Path,
    preview: Dict[str, Any],
) -> Dict[str, str]:
    target_bridge_dir.mkdir(parents=True, exist_ok=True)
    target_ui_dir = target_bridge_dir.parent / "ui"
    target_ui_dir.mkdir(parents=True, exist_ok=True)
    launcher_path = target_bridge_dir / "aui_bridge.py"
    protocol_path = target_bridge_dir / "aui_ui_protocol.json"
    config_path = target_bridge_dir / "aui_bridge_config.json"
    readme_path = target_bridge_dir / "README_BRIDGE.md"
    ui_runner_path = target_ui_dir / "ui_runner.py"
    ui_index_path = target_ui_dir / "index.html"
    ui_readme_path = target_ui_dir / "README_UI.md"

    launch_profile = _safe_dict(preview.get("launch_profile"))
    config = _build_bridge_config(
        thread_id=thread_id,
        project_root=project_root,
        launch_profile=launch_profile,
    )

    launcher_path.write_text(render_bridge_script(), encoding="utf-8")
    protocol_path.write_text(json.dumps(preview.get("ui_protocol") or {}, ensure_ascii=False, indent=2), encoding="utf-8")
    config_path.write_text(json.dumps(config, ensure_ascii=False, indent=2), encoding="utf-8")
    ui_runner_path.write_text(render_ui_runner_script(), encoding="utf-8")
    ui_index_path.write_text(render_embedded_ui_html(), encoding="utf-8")
    copied_assets_dir = _copy_template_assets(target_ui_dir)
    readme_path.write_text(_BRIDGE_README_CONTENT, encoding="utf-8")
    ui_readme_path.write_text(_UI_README_CONTENT, encoding="utf-8")

    result = {
        "launcher_path": str(launcher_path),
        "protocol_path": str(protocol_path),
        "config_path": str(config_path),
        "readme_path": str(readme_path),
        "bridge_dir": str(target_bridge_dir),
        "ui_runner_path": str(ui_runner_path),
        "ui_index_path": str(ui_index_path),
        "ui_readme_path": str(ui_readme_path),
        "ui_dir": str(target_ui_dir),
    }
    if copied_assets_dir is not None:
        result["ui_assets_dir"] = str(copied_assets_dir)
    return result


def sync_sidecar_logic_only(*, target_bridge_dir: Path) -> Dict[str, str]:
    """
    Sync runtime logic scripts only.
    This intentionally does NOT modify protocol/config files.
    """
    target_bridge_dir.mkdir(parents=True, exist_ok=True)
    target_ui_dir = target_bridge_dir.parent / "ui"
    target_ui_dir.mkdir(parents=True, exist_ok=True)

    launcher_path = target_bridge_dir / "aui_bridge.py"
    ui_runner_path = target_ui_dir / "ui_runner.py"

    launcher_path.write_text(render_bridge_script(), encoding="utf-8")
    ui_runner_path.write_text(render_ui_runner_script(), encoding="utf-8")

    return {
        "mode": "sync_logic_only",
        "launcher_path": str(launcher_path),
        "ui_runner_path": str(ui_runner_path),
        "bridge_dir": str(target_bridge_dir),
        "ui_dir": str(target_ui_dir),
    }
